### PR TITLE
Fix encoder implementation

### LINKED ISSUE #39: Fix encoder support
The current implementation of encoders on the `WPILibWSRobotRomi` assumes that exactly 2 encoders will be registered, and in the correct order (left, followed by right). Additionally, we did not take into account the DIO channels that were assigned to the encoder A/B inputs. This meant that robot code could create incorrectly mapped encoders and the Romi side of things would happily report encoder values for potentially incorrect WPILib encoder objects.

Support for software reversing of the encoders is also not implemented. This means that calling `setReverseDirection` on the WPILib encoder object would be a no-op.

### PR DESCRIPTION
**Pull request by zhiquanyeo**
This commit ensures that only appropriately registered encoders are
read (by checking the pin combinations supplied during encoder
registration). Additionally, this also implements encoder reversal

Resolves #39

### CODE REVIEW

File: src/romi-robot.ts [hunk 1]
```diff
@@ -534,7 +577,11 @@ export default class WPILibWSRomiRobot extends WPILibWSRobotBase {
                 encoderValue = buf.readInt16LE();
 
                 const lastValue = encoderInfo.lastRobotValue;
-                const delta = encoderValue - lastValue;
+
+                // Figure out if we should be reporting flipped values
+                const reverseMultiplier = (encoderInfo.isHardwareReversed ? -1 : 1) *
```
Comment (jpokornyiii) [inline src/romi-robot.ts:582]: I think you are assuming isHardwareReversed and isSoftwareReversed as created fields. I think this should have an:
If encoderInfo.isHardwareReversed != undefined && encoderinfo.isSoftwareReversed != underfined ....

Comment (zhiquanyeo) [reply src/romi-robot.ts:582]: It's actually fine, since `undefined` is false-y, so not having the field present is the same as being `false`
